version: "3.9"

services:
  db:
    image: postgres
    volumes: 
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  db_creator:
    build: .
    volumes:
      - .:/code
    depends_on: 
      - db