CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210810081955_InitTask') THEN
    CREATE TABLE task (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PKey" text NULL,
        "TaskNum" bigint NOT NULL,
        "ProjectId" bigint NOT NULL,
        "ReporterName" text NULL,
        "ActorName" text NULL,
        "CreatorName" text NULL,
        "Name" text NULL,
        "Description" text NULL,
        "Environment" text NULL,
        "Priority" text NULL,
        "Progress" text NULL,
        "DueDate" timestamp without time zone NOT NULL,
        "CompletionTime" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_task" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210810081955_InitTask') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210810081955_InitTask', '5.0.8');
    END IF;
END $$;
COMMIT;

